### ISSUE TITLE
metaset.py and marked.py should check if `posting.meta` exists before operating.

### ISSUE THREAD

**Issue by radsaggi** [Akuukis/beancount_plugin_utils#1]
Metaset assumes that the meta is always present. This is true for transactions and top level entries but not true for Posting meta since that is marked as optional. Ref [Beancount core/data](https://github.com/beancount/beancount/blob/master/beancount/core/data.py#L205). 

This broke my existing plugins :cry:

**Comment by Akuukis** [comment]
Oh, I didn't notice that's optional on Postings. Thanks for reference, will fix!

**Comment by Akuukis** [comment]
Done, see https://github.com/Akuukis/beancount_plugin_utils/releases/tag/v0.0.4

I will close now, feel free to reopen if it doesn't work for you.
